spring:
  datasource:
    url: jdbc:mysql://localhost:3306/codigo_exam?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    threads:
      max: 200
#logging:
#  level:
#    '[org.springframework]': trace